apiVersion: v1
kind: PersistentVolume
metadata:
  name: kapacitor-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kapacitordata"
